### ISSUE TITLE
fix lingering pitch errors

### ISSUE THREAD

**Issue by mmcghee18** [the-pudding/anthems#5]

**Comment by jadiehm** [comment]
Got through all the phrases. There are a couple of types of errors:
- **A.** Missing words/notes
- **B.** Parts that should be clipped out because it's external noise/echo
- **C.** Phrases that bleed into the next
- **D.** Pitches that need to be checked
- **E.** Bad audio altogether
- **F.** Word mistakes

### O say can you see
- **DROP? marvin-gaye_nba-allstar-game_1983:** missing "O", but rest still pretty different (A)
- **DROP chloe-bailey_world-series_2022:** might be missing holding the notes at the end (A)
- **DROP mariah-carey_super-bowl_2002:** missing "say" (A)
- [X] **aaron-lewis_world-series_2014:** check fall off at end (B)
- **DROP fantasia_ncaa-football-championship_2023:** missing "O" (A)
- [X] **alicia-keys_super-bowl_2013:** clipping errant parts (B)

### what so proudly we hailed
- [X] **lady-gaga_super-bowl_2016:** cut off echo spike (B)
- [X] **patti-labelle_world-series_2008:** check pitches (D)
- [X] **john-legend_nba-allstar-game_2013:** includes part of next phrase (C)

### at the twilight's last gleaming
- [X] **juanita-booker_inauguration_1981:** band comes in an messes it up (B, E)
- [X] **luke-bryan_super-bowl_2017:** check drop (D)

### whose broad stripes and bright stars
- [X] **aaron-lewis_world-series_2014:** check pitch on stars (D)
- [X] **whitney-houston_super-bowl_1991:** band comes in (B, E)

### through the perilous fight
- [X] **usher_nba-finals_2015:** missing words/notes (A)
- [X] **patti-labelle_world-series_2008:** echoes (B)

### o'er the ramparts we watched
- **DROP whitney-houston_super-bowl_1991:** funky toward the end (E)

### were so gallantly streaming
- [X] **eric-burton_world-series_2022:** word mistakes (F)
- [X] **renee-fleming_super-bowl_2014:** need to cut of last downward run (B)
- [X] **juanita-booker_inauguration_1981:** band comes in at end (B, E)
- [X] **marvin-gaye_nba-allstar-game_1983:** loses "streaming" (A)
- [X] **jordan-smith_nfl-regular-season_2023:** check pitch drop (D)

### and the rocket's red glare
- [X] **chloe-bailey_world-series_2022:** check pitch drop (D)
- **DROP aaron-lewis_world-series_2014:** very muffled (E)
- [X] **peabo-bryson_world-series_1992:** check pitch drop (D)
- [X] **demi-lovato_world-series_2015:** check pitch drop (D)

### the bombs bursting in air
- [X] **madison-watkins_world-series_2022:** check pitch "in air" (D)
- **DROP john-oates_world-series_2008:** audio cuts out (E)
- **DROP chloe-bailey_world-series_2022:** missing first notes (A)
- **DROP mickey-guyton_world-series_2023:** rough quality (E)
- **DROP marvin-gaye_nba-allstar-game_1983:** missing "the bombs" (A)

### gave proof through the night
- **DROP cassadee-pope_stanley-cup-playoffs_2023:** messed up by cheers (B, E)
- **DROP rachel-platten_world-series_2016:** cuts off "night" (A)
- **DROP mary-j-blige_world-series_2009:** missing "through the" (A)

### that our flag was still there
- [X] **lady-gaga_super-bowl_2016:** goes into next phrase (C)

### o say does that star spangled
- [X] **jordin-sparks_mlb-allstar-game_2011:** bleeds into next phrase (C)
- [X] **anthony-hamilton_nba-allstar-game_2019:** "spangled" cut out? (A)
- **DROP chloe-bailey_world-series_2022:** bad audio (E)

### banner yet wave
- **DROP mary-j-blige_world-series_2013:** crowd noise (B, E)
- [X] **jennifer-hudson_super-bowl_2009:** bleeds into next phrase (C)

### and the home of the brave
- **CHECK PROCESSING, PITCH FILE LOOKS CORRECT idina-menzel_mlb-allstar-game_2014:** check pitches (D)
- [X] **demi-lovato_world-series_2015:** check pitches (D)
- **DROP cher_super-bowl_1999:** band comes in (B, E)
- [X] **mickey-guyton_super-bowl_2022:** jet noise spike (B)
